### ISSUE TITLE
Logging file

### ISSUE THREAD

**Issue by trvrb** [blab/zika-seq#10]
This is dangerous: https://github.com/blab/zika-seq/blob/master/pipeline/scripts/pipeline.py#L244

You don't want two simultaneous runs of `pipeline.py` to try to write to the same `log.txt` file. Instead, just write to standard out. This debugs nicely locally and will automatically write to files like `slurm-50293878.out` on Rhino. Or if there's an important reason to keep this separate from standard out, append the time to this file to ensure uniqueness.

**Comment by trvrb** [comment]
I see now that this has checks to see if the file already exists, and if it does it appends rather than writes to it. Presuming in this case there's little risk of conflict, but not fully sure. @barneypotter24 --- please close this issue if you can confirm that this won't result in errors.

**Comment by barneypotter24** [comment]
Looking at this, I wrote the logfile with the intention of doing 1 run with all the samples at once, however that is no longer the case. I am prepending the sample name to the beginning of the log file (`VI2-log.txt`), since in most cases we will be batching a single library run, so that should differentiate files.  I chose to keep things written to a log file because I think it makes it easier keep track of associating a run to specific output. I think slurm job IDs are hard to keep track of when submitting more than ~10 jobs. @trvrb: will this change work or do you think it makes too many output files for a run?

**Comment by barneypotter24** [comment]
Logging files are no longer used.
